import type { EnemyTemplate } from './types';

export const ENEMY_TEMPLATES: EnemyTemplate[] = [
	// CR 0
	{ name: 'Bat', ac: 12, hp: 1, cr: '0', monsterType: 'Beast' },
	{ name: 'Commoner', ac: 10, hp: 4, cr: '0', monsterType: 'Humanoid' },
	{ name: 'Rat', ac: 10, hp: 1, cr: '0', monsterType: 'Beast' },
	// CR 1/8
	{ name: 'Giant Rat', ac: 12, hp: 7, cr: '1/8', monsterType: 'Beast' },
	{ name: 'Kobold', ac: 12, hp: 5, cr: '1/8', monsterType: 'Humanoid' },
	{ name: 'Stirge', ac: 14, hp: 2, cr: '1/8', monsterType: 'Beast' },
	{ name: 'Bandit', ac: 12, hp: 11, cr: '1/8', monsterType: 'Humanoid' },
	{ name: 'Guard', ac: 16, hp: 11, cr: '1/8', monsterType: 'Humanoid' },
	// CR 1/4
	{ name: 'Boar', ac: 11, hp: 11, cr: '1/4', monsterType: 'Beast' },
	{ name: 'Cultist', ac: 12, hp: 9, cr: '1/8', monsterType: 'Humanoid' },
	{ name: 'Giant Wolf Spider', ac: 13, hp: 11, cr: '1/4', monsterType: 'Beast' },
	{ name: 'Goblin', ac: 15, hp: 7, cr: '1/4', monsterType: 'Humanoid' },
	{ name: 'Skeleton', ac: 13, hp: 13, cr: '1/4', monsterType: 'Undead' },
	{ name: 'Wolf', ac: 13, hp: 11, cr: '1/4', monsterType: 'Beast' },
	{ name: 'Zombie', ac: 8, hp: 22, cr: '1/4', monsterType: 'Undead' },
	{ name: 'Swarm of Rats', ac: 10, hp: 24, cr: '1/4', monsterType: 'Beast' },
	// CR 1/2
	{ name: 'Black Bear', ac: 11, hp: 19, cr: '1/2', monsterType: 'Beast' },
	{ name: 'Crocodile', ac: 12, hp: 19, cr: '1/2', monsterType: 'Beast' },
	{ name: 'Gnoll', ac: 15, hp: 22, cr: '1/2', monsterType: 'Humanoid' },
	{ name: 'Hobgoblin', ac: 18, hp: 11, cr: '1/2', monsterType: 'Humanoid' },
	{ name: 'Lizardfolk', ac: 15, hp: 22, cr: '1/2', monsterType: 'Humanoid' },
	{ name: 'Orc', ac: 13, hp: 15, cr: '1/2', monsterType: 'Humanoid' },
	{ name: 'Sahuagin', ac: 12, hp: 22, cr: '1/2', monsterType: 'Humanoid' },
	// CR 1
	{ name: 'Brown Bear', ac: 11, hp: 34, cr: '1', monsterType: 'Beast' },
	{ name: 'Bugbear', ac: 16, hp: 27, cr: '1', monsterType: 'Humanoid' },
	{ name: 'Dire Wolf', ac: 14, hp: 37, cr: '1', monsterType: 'Beast' },
	{ name: 'Dryad', ac: 11, hp: 22, cr: '1', monsterType: 'Fey' },
	{ name: 'Ghoul', ac: 12, hp: 22, cr: '1', monsterType: 'Undead' },
	{ name: 'Giant Spider', ac: 14, hp: 26, cr: '1', monsterType: 'Beast' },
	{ name: 'Harpy', ac: 11, hp: 38, cr: '1', monsterType: 'Monstrosity' },
	{ name: 'Hippogriff', ac: 11, hp: 19, cr: '1', monsterType: 'Monstrosity' },
	// CR 2
	{ name: 'Ankheg', ac: 14, hp: 39, cr: '2', monsterType: 'Monstrosity' },
	{ name: 'Bandit Captain', ac: 15, hp: 65, cr: '2', monsterType: 'Humanoid' },
	{ name: 'Berserker', ac: 13, hp: 67, cr: '2', monsterType: 'Humanoid' },
	{ name: 'Ettercap', ac: 13, hp: 44, cr: '2', monsterType: 'Monstrosity' },
	{ name: 'Gargoyle', ac: 15, hp: 52, cr: '2', monsterType: 'Elemental' },
	{ name: 'Ghast', ac: 13, hp: 36, cr: '2', monsterType: 'Undead' },
	{ name: 'Ogre', ac: 11, hp: 59, cr: '2', monsterType: 'Giant' },
	{ name: 'Sea Hag', ac: 14, hp: 52, cr: '2', monsterType: 'Fey' },
	{ name: 'Wererat', ac: 12, hp: 33, cr: '2', monsterType: 'Humanoid' },
	{ name: 'Will-o-Wisp', ac: 19, hp: 22, cr: '2', monsterType: 'Undead' },
	// CR 3
	{ name: 'Basilisk', ac: 15, hp: 52, cr: '3', monsterType: 'Monstrosity' },
	{ name: 'Displacer Beast', ac: 13, hp: 85, cr: '3', monsterType: 'Monstrosity' },
	{ name: 'Doppelganger', ac: 14, hp: 52, cr: '3', monsterType: 'Monstrosity' },
	{ name: 'Green Hag', ac: 14, hp: 82, cr: '3', monsterType: 'Fey' },
	{ name: 'Hell Hound', ac: 15, hp: 45, cr: '3', monsterType: 'Fiend' },
	{ name: 'Knight', ac: 18, hp: 52, cr: '3', monsterType: 'Humanoid' },
	{ name: 'Manticore', ac: 14, hp: 68, cr: '3', monsterType: 'Monstrosity' },
	{ name: 'Mummy', ac: 11, hp: 58, cr: '3', monsterType: 'Undead' },
	{ name: 'Owlbear', ac: 13, hp: 59, cr: '3', monsterType: 'Monstrosity' },
	{ name: 'Veteran', ac: 17, hp: 65, cr: '3', monsterType: 'Humanoid' },
	{ name: 'Wight', ac: 14, hp: 45, cr: '3', monsterType: 'Undead' },
	{ name: 'Werewolf', ac: 11, hp: 58, cr: '3', monsterType: 'Humanoid' },
	// CR 4-6
	{ name: 'Banshee', ac: 12, hp: 58, cr: '4', monsterType: 'Undead' },
	{ name: 'Chuul', ac: 16, hp: 93, cr: '4', monsterType: 'Aberration' },
	{ name: 'Ettin', ac: 12, hp: 85, cr: '4', monsterType: 'Giant' },
	{ name: 'Ghost', ac: 11, hp: 45, cr: '4', monsterType: 'Undead' },
	{ name: 'Lamia', ac: 13, hp: 97, cr: '4', monsterType: 'Monstrosity' },
	{ name: 'Succubus/Incubus', ac: 13, hp: 66, cr: '4', monsterType: 'Fiend' },
	{ name: 'Cyclops', ac: 14, hp: 138, cr: '6', monsterType: 'Giant' },
	{ name: 'Medusa', ac: 15, hp: 127, cr: '6', monsterType: 'Monstrosity' },
	{ name: 'Hill Giant', ac: 13, hp: 105, cr: '5', monsterType: 'Giant' },
	{ name: 'Revenant', ac: 13, hp: 136, cr: '5', monsterType: 'Undead' },
	{ name: 'Troll', ac: 15, hp: 84, cr: '5', monsterType: 'Giant' },
	{ name: 'Vampire Spawn', ac: 13, hp: 82, cr: '5', monsterType: 'Undead' },
	{ name: 'Wraith', ac: 13, hp: 67, cr: '5', monsterType: 'Undead' },
	// CR 7-10
	{ name: 'Mind Flayer', ac: 15, hp: 71, cr: '7', monsterType: 'Aberration' },
	{ name: 'Oni', ac: 16, hp: 110, cr: '7', monsterType: 'Giant' },
	{ name: 'Stone Giant', ac: 17, hp: 126, cr: '7', monsterType: 'Giant' },
	{ name: 'Young Black Dragon', ac: 18, hp: 127, cr: '7', monsterType: 'Dragon' },
	{ name: 'Chain Devil', ac: 16, hp: 85, cr: '8', monsterType: 'Fiend' },
	{ name: 'Frost Giant', ac: 15, hp: 138, cr: '8', monsterType: 'Giant' },
	{ name: 'Hydra', ac: 15, hp: 172, cr: '8', monsterType: 'Monstrosity' },
	{ name: 'Young Blue Dragon', ac: 18, hp: 152, cr: '9', monsterType: 'Dragon' },
	{ name: 'Young Green Dragon', ac: 18, hp: 136, cr: '8', monsterType: 'Dragon' },
	{ name: 'Fire Giant', ac: 18, hp: 162, cr: '9', monsterType: 'Giant' },
	{ name: 'Young Red Dragon', ac: 18, hp: 178, cr: '10', monsterType: 'Dragon' },
	// CR 11+
	{ name: 'Archmage', ac: 12, hp: 99, cr: '12', monsterType: 'Humanoid' },
	{ name: 'Beholder', ac: 18, hp: 180, cr: '13', monsterType: 'Aberration' },
	{ name: 'Storm Giant', ac: 16, hp: 230, cr: '13', monsterType: 'Giant' },
	{ name: 'Vampire', ac: 16, hp: 144, cr: '13', monsterType: 'Undead' },
	{ name: 'Adult Black Dragon', ac: 19, hp: 195, cr: '14', monsterType: 'Dragon' },
	{ name: 'Adult Green Dragon', ac: 19, hp: 207, cr: '15', monsterType: 'Dragon' },
	{ name: 'Adult Blue Dragon', ac: 19, hp: 225, cr: '16', monsterType: 'Dragon' },
	{ name: 'Adult Red Dragon', ac: 19, hp: 256, cr: '17', monsterType: 'Dragon' },
	{ name: 'Lich', ac: 17, hp: 135, cr: '21', monsterType: 'Undead' },
	{ name: 'Ancient Red Dragon', ac: 22, hp: 546, cr: '24', monsterType: 'Dragon' },
];

export const MONSTER_TYPES = ['All', ...new Set(ENEMY_TEMPLATES.map((e) => e.monsterType))].sort();

export const CONDITIONS = [
	'Blinded',
	'Charmed',
	'Concentrating',
	'Deafened',
	'Dead',
	'Exhausted',
	'Frightened',
	'Grappled',
	'Incapacitated',
	'Invisible',
	'Paralyzed',
	'Petrified',
	'Poisoned',
	'Prone',
	'Restrained',
	'Stunned',
	'Unconscious',
] as const;
