// Server logic for /unsubscribe/[token] — the link at the bottom of every admin broadcast email,
// for both DM and player recipients. Unsubscribing happens on the POST action, not on page load —
// see the verify-email route's comment for why (mail providers' link-scanners prefetch GETs and
// would silently unsubscribe people who never clicked anything). load() only does a read-only
// lookup to show whose address this is before they confirm. DM and player tokens are generated by
// the same generateToken() and stored in separate collections, so trying both lookups is safe —
// a real collision is astronomically unlikely.
import type { Actions, PageServerLoad } from './$types';
import { getEmailByUnsubscribeToken, unsubscribeByToken } from '$lib/server/dmModel';
import {
	getEmailByPlayerUnsubscribeToken,
	unsubscribePlayerByToken
} from '$lib/server/playerModel';

export const load: PageServerLoad = async ({ params }) => {
	const email =
		(await getEmailByUnsubscribeToken(params.token)) ??
		(await getEmailByPlayerUnsubscribeToken(params.token));
	return { email };
};

export const actions: Actions = {
	default: async ({ params }) => {
		const dmResult = await unsubscribeByToken(params.token);
		if (dmResult.ok) return dmResult;
		return await unsubscribePlayerByToken(params.token);
	}
};
